In [36]:

import matplotlib.pyplot as plt
import numpy as np
from python.dmd_class import DMD


In [37]:
n = 10
m = 9
# Fit the DMD object to the data
X = np.zeros((n, m))
X.shape[0]

for i in range(n):
    for j in range(m):
        X[i, j] = j + i

print(X)


[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 8.  9. 10. 11. 12. 13. 14. 15. 16.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17.]]


In [38]:
# Create a DMD object
dmd = DMD()
dmd.fit(X)

X1 = X[:, :-1]
X2 = dmd.A @ X1





AttributeError: 'DMD' object has no attribute 'A_tilde'