In [8]:

import matplotlib.pyplot as plt
import numpy as np
from dmd_class import DMD


In [9]:
## Creating a toy problem

n_points    = 10
n_snapshots = 9

# Fit the DMD object to the data
X = np.zeros((n_points, n_snapshots))

for s in range(n_snapshots):
    for p in range(n_points):
        X[p, s] = p + s

print(X)


[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 8.  9. 10. 11. 12. 13. 14. 15. 16.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17.]]


In [10]:
# Create a DMD object
dmd = DMD()
dmd.fit(X)

X1 = X[:,n_snapshots-1]
for t in range(n_snapshots,n_snapshots+3):
    X2 = dmd.predict(X1)
    print(X2.real)
    X1 = X2




[ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
