In [1]:
import matplotlib.pyplot as plt
import numpy as np
from dmd_class import DMD
import scipy.io 

In [2]:
file_path = '../DATA/FLUIDS/CYLINDER_ALL.mat'
mat = scipy.io.loadmat(file_path)
print(mat.keys())
print(mat['UALL'].shape)
X = mat['UALL']


dict_keys(['__header__', '__version__', '__globals__', 'UALL', 'UEXTRA', 'VALL', 'VEXTRA', 'VORTALL', 'VORTEXTRA', 'm', 'n', 'nx', 'ny'])
(89351, 151)


In [3]:
# Create a DMD object
dmd = DMD()
dmd.fit(X)
n_points,n_snapshots = X.shape


apos pinv
apos A
[1.01949396 1.01902051 1.01845852 ... 1.04747487 1.04880354 1.05031752]
[1.01941204 1.01893859 1.01837658 ... 1.04626042 1.04759324 1.04910734]
[1.01933173 1.01885826 1.01829624 ... 1.04507039 1.04640728 1.04792149]


In [4]:
X1 = X[:,n_snapshots-1]
for t in range(n_snapshots,n_snapshots+3):
    X2 = dmd.predict(X1)
    print(X2.real)
    X1 = X2

[1.01949396 1.01902051 1.01845852 ... 1.04747487 1.04880354 1.05031752]
[1.01941204 1.01893859 1.01837658 ... 1.04626042 1.04759324 1.04910734]
[1.01933173 1.01885826 1.01829624 ... 1.04507039 1.04640728 1.04792149]
